#!/usr/bin/env node

var child_process = require('child_process'),
    path = require('path'),
    _ = require('underscore'),
    fs = require('fs'),
    glob = require('minimatch'),
    temp = require('temp');

function runCmd(cmd, opts, cb) {
  if (!cb) {
    cb = opts;
    opts = { cwd: path.dirname(__dirname) };
  }
  var cp = child_process.exec(cmd, opts, function(err, stdout, stderr) {
    cb(err, stdout, stderr);
  });
}

// path to automation_tests
const testPath = path.join(path.dirname(__dirname), "automation-tests");

// python arguments common to all tests
var globalPythonArgs = {
  "-m": "py.test",
  "--credentials": path.join(testPath, "credentials.yaml"),
  "--saucelabs": path.join(testPath, "sauce.yaml"),
  "--destructive": null
};

// python arguments specific to different test classes
var testSpecificPythonArgs = {
  "123done": {
    "--baseurl": "http://dev.123done.org",
    "-q": "123done"
  },
  "browserid": {
    "--baseurl": "http://dev.123done.org",
    "-q": "browserid"
  },
  "myfavoritebeer": {
    "--baseurl": "http://dev.myfavoritebeer.org",
    "-q": "myfavoritebeer"
  }
};

// python arguments specific to different browser/os combos
var browserSpecificPythonArgs = {
  "linux_ffx_13": {
    '--platform': 'LINUX',
    '--browsername': 'firefox',
    '--browserver': 13
  },
  "linux_opera_12": {
    '--platform': 'LINUX',
    '--browsername': 'opera',
    '--browserver': '12',
  },
  "osx_firefox_14": {
    '--platform': 'MAC',
    '--browsername':'firefox',
    '--browserver':'14'
  },
  "vista_chrome": {
    '--platform':'VISTA',
    '--browsername':'chrome'
  },
  "vista_firefox_13": {
    '--platform':'VISTA',
    '--browsername':'firefox',
    '--browserver':'13'
  },
  "vista_ie_9": {
    '--platform':'Windows 2008',
    '--browsername':'internet explorer',
    '--browserver':'9'
  },
  "xp_ie_8": {
    '--platform':'XP',
    '--browsername': 'internet explorer',
    '--browserver':'8'
  }
};

function escape(val) {
  return '"'+val.replace(/(["'$`\\])/g,'\\$1')+'"';
};

// now write a yaml file with sauce creds
function writeSauceYAML() {
  var envVars = {
    'PERSONA_SAUCE_USER': 'username',
    'PERSONA_SAUCE_PASSWORD': 'password',
    'PERSONA_SAUCE_APIKEY': 'api-key'
  };

  var fileContents = "";
  Object.keys(envVars).forEach(function(key) {
    if (!process.env[key]) throw "missing sauce labs creds from environment";
    fileContents += envVars[key] + ": " + process.env[key] + "\n"
  });
  fs.writeFileSync(path.join(testPath, "sauce.yaml"), fileContents);
}

exports.run = function(opts, cb) {
  var processesRunning;
  var testReports = [];

  opts = opts || {};

  writeSauceYAML();

  Object.keys(browserSpecificPythonArgs).forEach(function(browser) {
    if (opts.browser && !glob(browser, opts.browser.toString())) return;
    var browserArgs = browserSpecificPythonArgs[browser];

    Object.keys(testSpecificPythonArgs).forEach(function(test) {
      if (opts['test-group'] && !glob(test, (opts['test-group']).toString())) return;

      var htmlReportPath = temp.path({suffix: '.pdf'});
      var testArgs = testSpecificPythonArgs[test];

      // build up the command line arguments
      var cmdargsObj = {};
      _.extend(cmdargsObj, globalPythonArgs, testArgs, browserArgs,
               { '--webqareport': htmlReportPath });
      var cmdargs = "";
      Object.keys(cmdargsObj).forEach(function(flag) {
        var spc = " ";
        if (flag.substr(2) === '--') spc = "=";
        if (null === cmdargsObj[flag]) {
          cmdargs += flag + " ";
        } else {
          cmdargs += flag + spc + escape(cmdargsObj[flag].toString()) + " ";
        }
      });

      console.log("STARTED: " + browser + "/" + test);
      var startTime = new Date();
      processesRunning++;
      runCmd("bid_selenium/bin/python " + cmdargs, { cwd: testPath }, function(err, stdout, stderr) {
        var report = {
          browser: browser,
          test: test,
          duration: ((new Date() - startTime) / 1000.0),
          stdout: stdout,
          stderr: stderr,
          err: err,
          passed: !err
        };

        var htmlReportContents = fs.readFileSync(htmlReportPath);

        // XXX parse out interesting stuff from htmlReport and update report

        console.log((report.passed ? "PASSED" : "FAILED") + ": " + browser + "/" + test,
                    report.duration.toFixed(2) + "s");

        testReports.push(report);

        // remove artifacts
        fs.unlink(htmlReportPath);

        if (--processesRunning === 0) {
          fs.unlink(path.join(testPath, "sauce.yaml"));
          if (cb) cb(null, testReports);
          console.log(testReports);
        }
      });
    });
  });
};

// if we're invoked from the command line, do command liney things
if (process.argv[1] === __filename) {
  process.on('uncaughtException', function(err) {
    console.log("OH NOES", err);
    process.exit(1);
  });

  var argv = require('optimist')
    .usage('Run selenium tests via sauce labs.\nUsage: $0')
    .alias('help', 'h')
    .describe('help', 'display this usage message')
    .alias('list-browsers', 'lb')
    .describe('lb', 'list available browsers to test on')
    .alias('browser', 'b')
    .describe('browser', 'specify which browser to run tests on (globs supported)')
    .default('browser', "*")
    .alias('list-test-groups', 'lt')
    .describe('list-test-groups', 'list available groups of tests that can be run')
    .alias('test-group', 't')
    .describe('test-group', 'specify which test groups to run (globs supported)')
    .default("test-group", "*");

  var args = argv.argv;

  if (args.h) {
    argv.showHelp();
    process.exit(0);
  }

  if (args.lb) {
    console.log("available browsers:");
    console.log("   * " + Object.keys(browserSpecificPythonArgs).join("\n   * "));
    process.exit(0);
  }

  if (args.lt) {
    console.log("available tests:");
    console.log("   * " + Object.keys(testSpecificPythonArgs).join("\n   * "));
    process.exit(0);
  }

  exports.run(_.extend({}, args));
}
